spring:
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=materiales_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true

server:
  port: 9000
